# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sts_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sts_v1.proto',
  package='sts.ai.protocol.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csts_v1.proto\x12\x12sts.ai.protocol.v1\"\xc7\x01\n\tGameState\x12\x10\n\x08md5_seed\x18\x01 \x01(\t\x12\x11\n\tcharacter\x18\x02 \x01(\t\x12\x0b\n\x03\x61\x63t\x18\x03 \x01(\x05\x12\r\n\x05\x66loor\x18\x04 \x01(\x05\x12\x11\n\tplayer_hp\x18\x05 \x01(\x05\x12\x15\n\rplayer_max_hp\x18\x06 \x01(\x05\x12\x15\n\rplayer_energy\x18\x07 \x01(\x05\x12\x12\n\nhand_cards\x18\x08 \x03(\t\x12\x15\n\rvalid_actions\x18\t \x03(\x05\x12\r\n\x05stage\x18\n \x01(\t\"7\n\rActionCommand\x12\x13\n\x0b\x61\x63tion_type\x18\x01 \x01(\t\x12\x11\n\taction_id\x18\x02 \x01(\x05\"\xd7\x01\n\x0fProtocolMessage\x12\x14\n\x0cmessage_type\x18\x01 \x01(\t\x12\x13\n\x0bsequence_id\x18\x02 \x01(\x05\x12\x1c\n\x14is_waiting_for_input\x18\x03 \x01(\x08\x12\x31\n\ngame_state\x18\x04 \x01(\x0b\x32\x1d.sts.ai.protocol.v1.GameState\x12\x35\n\naction_cmd\x18\x05 \x01(\x0b\x32!.sts.ai.protocol.v1.ActionCommand\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x62\x06proto3'
)




_GAMESTATE = _descriptor.Descriptor(
  name='GameState',
  full_name='sts.ai.protocol.v1.GameState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='md5_seed', full_name='sts.ai.protocol.v1.GameState.md5_seed', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='character', full_name='sts.ai.protocol.v1.GameState.character', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='act', full_name='sts.ai.protocol.v1.GameState.act', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='floor', full_name='sts.ai.protocol.v1.GameState.floor', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='player_hp', full_name='sts.ai.protocol.v1.GameState.player_hp', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='player_max_hp', full_name='sts.ai.protocol.v1.GameState.player_max_hp', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='player_energy', full_name='sts.ai.protocol.v1.GameState.player_energy', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hand_cards', full_name='sts.ai.protocol.v1.GameState.hand_cards', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valid_actions', full_name='sts.ai.protocol.v1.GameState.valid_actions', index=8,
      number=9, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stage', full_name='sts.ai.protocol.v1.GameState.stage', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=236,
)


_ACTIONCOMMAND = _descriptor.Descriptor(
  name='ActionCommand',
  full_name='sts.ai.protocol.v1.ActionCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action_type', full_name='sts.ai.protocol.v1.ActionCommand.action_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action_id', full_name='sts.ai.protocol.v1.ActionCommand.action_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=293,
)


_PROTOCOLMESSAGE = _descriptor.Descriptor(
  name='ProtocolMessage',
  full_name='sts.ai.protocol.v1.ProtocolMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='sts.ai.protocol.v1.ProtocolMessage.message_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequence_id', full_name='sts.ai.protocol.v1.ProtocolMessage.sequence_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_waiting_for_input', full_name='sts.ai.protocol.v1.ProtocolMessage.is_waiting_for_input', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game_state', full_name='sts.ai.protocol.v1.ProtocolMessage.game_state', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action_cmd', full_name='sts.ai.protocol.v1.ProtocolMessage.action_cmd', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='sts.ai.protocol.v1.ProtocolMessage.timestamp', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=511,
)

_PROTOCOLMESSAGE.fields_by_name['game_state'].message_type = _GAMESTATE
_PROTOCOLMESSAGE.fields_by_name['action_cmd'].message_type = _ACTIONCOMMAND
DESCRIPTOR.message_types_by_name['GameState'] = _GAMESTATE
DESCRIPTOR.message_types_by_name['ActionCommand'] = _ACTIONCOMMAND
DESCRIPTOR.message_types_by_name['ProtocolMessage'] = _PROTOCOLMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameState = _reflection.GeneratedProtocolMessageType('GameState', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTATE,
  '__module__' : 'sts_v1_pb2'
  # @@protoc_insertion_point(class_scope:sts.ai.protocol.v1.GameState)
  })
_sym_db.RegisterMessage(GameState)

ActionCommand = _reflection.GeneratedProtocolMessageType('ActionCommand', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONCOMMAND,
  '__module__' : 'sts_v1_pb2'
  # @@protoc_insertion_point(class_scope:sts.ai.protocol.v1.ActionCommand)
  })
_sym_db.RegisterMessage(ActionCommand)

ProtocolMessage = _reflection.GeneratedProtocolMessageType('ProtocolMessage', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCOLMESSAGE,
  '__module__' : 'sts_v1_pb2'
  # @@protoc_insertion_point(class_scope:sts.ai.protocol.v1.ProtocolMessage)
  })
_sym_db.RegisterMessage(ProtocolMessage)


# @@protoc_insertion_point(module_scope)
