// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sts_v1.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sts_5fv1_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sts_5fv1_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sts_5fv1_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sts_5fv1_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sts_5fv1_2eproto;
namespace sts {
namespace ai {
namespace protocol {
namespace v1 {
class ActionCommand;
class ActionCommandDefaultTypeInternal;
extern ActionCommandDefaultTypeInternal _ActionCommand_default_instance_;
class GameState;
class GameStateDefaultTypeInternal;
extern GameStateDefaultTypeInternal _GameState_default_instance_;
class ProtocolMessage;
class ProtocolMessageDefaultTypeInternal;
extern ProtocolMessageDefaultTypeInternal _ProtocolMessage_default_instance_;
}  // namespace v1
}  // namespace protocol
}  // namespace ai
}  // namespace sts
PROTOBUF_NAMESPACE_OPEN
template<> ::sts::ai::protocol::v1::ActionCommand* Arena::CreateMaybeMessage<::sts::ai::protocol::v1::ActionCommand>(Arena*);
template<> ::sts::ai::protocol::v1::GameState* Arena::CreateMaybeMessage<::sts::ai::protocol::v1::GameState>(Arena*);
template<> ::sts::ai::protocol::v1::ProtocolMessage* Arena::CreateMaybeMessage<::sts::ai::protocol::v1::ProtocolMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sts {
namespace ai {
namespace protocol {
namespace v1 {

// ===================================================================

class GameState PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sts.ai.protocol.v1.GameState) */ {
 public:
  inline GameState() : GameState(nullptr) {}
  virtual ~GameState();

  GameState(const GameState& from);
  GameState(GameState&& from) noexcept
    : GameState() {
    *this = ::std::move(from);
  }

  inline GameState& operator=(const GameState& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameState& operator=(GameState&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GameState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GameState* internal_default_instance() {
    return reinterpret_cast<const GameState*>(
               &_GameState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GameState& a, GameState& b) {
    a.Swap(&b);
  }
  inline void Swap(GameState* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GameState* New() const final {
    return CreateMaybeMessage<GameState>(nullptr);
  }

  GameState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GameState>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GameState& from);
  void MergeFrom(const GameState& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameState* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sts.ai.protocol.v1.GameState";
  }
  protected:
  explicit GameState(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sts_5fv1_2eproto);
    return ::descriptor_table_sts_5fv1_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHandCardsFieldNumber = 8,
    kValidActionsFieldNumber = 9,
    kMd5SeedFieldNumber = 1,
    kCharacterFieldNumber = 2,
    kStageFieldNumber = 10,
    kActFieldNumber = 3,
    kFloorFieldNumber = 4,
    kPlayerHpFieldNumber = 5,
    kPlayerMaxHpFieldNumber = 6,
    kPlayerEnergyFieldNumber = 7,
  };
  // repeated string hand_cards = 8;
  int hand_cards_size() const;
  private:
  int _internal_hand_cards_size() const;
  public:
  void clear_hand_cards();
  const std::string& hand_cards(int index) const;
  std::string* mutable_hand_cards(int index);
  void set_hand_cards(int index, const std::string& value);
  void set_hand_cards(int index, std::string&& value);
  void set_hand_cards(int index, const char* value);
  void set_hand_cards(int index, const char* value, size_t size);
  std::string* add_hand_cards();
  void add_hand_cards(const std::string& value);
  void add_hand_cards(std::string&& value);
  void add_hand_cards(const char* value);
  void add_hand_cards(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& hand_cards() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_hand_cards();
  private:
  const std::string& _internal_hand_cards(int index) const;
  std::string* _internal_add_hand_cards();
  public:

  // repeated int32 valid_actions = 9;
  int valid_actions_size() const;
  private:
  int _internal_valid_actions_size() const;
  public:
  void clear_valid_actions();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_valid_actions(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_valid_actions() const;
  void _internal_add_valid_actions(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_valid_actions();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 valid_actions(int index) const;
  void set_valid_actions(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_valid_actions(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      valid_actions() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_valid_actions();

  // string md5_seed = 1;
  void clear_md5_seed();
  const std::string& md5_seed() const;
  void set_md5_seed(const std::string& value);
  void set_md5_seed(std::string&& value);
  void set_md5_seed(const char* value);
  void set_md5_seed(const char* value, size_t size);
  std::string* mutable_md5_seed();
  std::string* release_md5_seed();
  void set_allocated_md5_seed(std::string* md5_seed);
  private:
  const std::string& _internal_md5_seed() const;
  void _internal_set_md5_seed(const std::string& value);
  std::string* _internal_mutable_md5_seed();
  public:

  // string character = 2;
  void clear_character();
  const std::string& character() const;
  void set_character(const std::string& value);
  void set_character(std::string&& value);
  void set_character(const char* value);
  void set_character(const char* value, size_t size);
  std::string* mutable_character();
  std::string* release_character();
  void set_allocated_character(std::string* character);
  private:
  const std::string& _internal_character() const;
  void _internal_set_character(const std::string& value);
  std::string* _internal_mutable_character();
  public:

  // string stage = 10;
  void clear_stage();
  const std::string& stage() const;
  void set_stage(const std::string& value);
  void set_stage(std::string&& value);
  void set_stage(const char* value);
  void set_stage(const char* value, size_t size);
  std::string* mutable_stage();
  std::string* release_stage();
  void set_allocated_stage(std::string* stage);
  private:
  const std::string& _internal_stage() const;
  void _internal_set_stage(const std::string& value);
  std::string* _internal_mutable_stage();
  public:

  // int32 act = 3;
  void clear_act();
  ::PROTOBUF_NAMESPACE_ID::int32 act() const;
  void set_act(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_act() const;
  void _internal_set_act(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 floor = 4;
  void clear_floor();
  ::PROTOBUF_NAMESPACE_ID::int32 floor() const;
  void set_floor(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_floor() const;
  void _internal_set_floor(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 player_hp = 5;
  void clear_player_hp();
  ::PROTOBUF_NAMESPACE_ID::int32 player_hp() const;
  void set_player_hp(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_player_hp() const;
  void _internal_set_player_hp(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 player_max_hp = 6;
  void clear_player_max_hp();
  ::PROTOBUF_NAMESPACE_ID::int32 player_max_hp() const;
  void set_player_max_hp(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_player_max_hp() const;
  void _internal_set_player_max_hp(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 player_energy = 7;
  void clear_player_energy();
  ::PROTOBUF_NAMESPACE_ID::int32 player_energy() const;
  void set_player_energy(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_player_energy() const;
  void _internal_set_player_energy(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:sts.ai.protocol.v1.GameState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> hand_cards_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > valid_actions_;
  mutable std::atomic<int> _valid_actions_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr md5_seed_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr character_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stage_;
  ::PROTOBUF_NAMESPACE_ID::int32 act_;
  ::PROTOBUF_NAMESPACE_ID::int32 floor_;
  ::PROTOBUF_NAMESPACE_ID::int32 player_hp_;
  ::PROTOBUF_NAMESPACE_ID::int32 player_max_hp_;
  ::PROTOBUF_NAMESPACE_ID::int32 player_energy_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sts_5fv1_2eproto;
};
// -------------------------------------------------------------------

class ActionCommand PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sts.ai.protocol.v1.ActionCommand) */ {
 public:
  inline ActionCommand() : ActionCommand(nullptr) {}
  virtual ~ActionCommand();

  ActionCommand(const ActionCommand& from);
  ActionCommand(ActionCommand&& from) noexcept
    : ActionCommand() {
    *this = ::std::move(from);
  }

  inline ActionCommand& operator=(const ActionCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActionCommand& operator=(ActionCommand&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ActionCommand& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ActionCommand* internal_default_instance() {
    return reinterpret_cast<const ActionCommand*>(
               &_ActionCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ActionCommand& a, ActionCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(ActionCommand* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActionCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ActionCommand* New() const final {
    return CreateMaybeMessage<ActionCommand>(nullptr);
  }

  ActionCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ActionCommand>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ActionCommand& from);
  void MergeFrom(const ActionCommand& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActionCommand* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sts.ai.protocol.v1.ActionCommand";
  }
  protected:
  explicit ActionCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sts_5fv1_2eproto);
    return ::descriptor_table_sts_5fv1_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kActionTypeFieldNumber = 1,
    kActionIdFieldNumber = 2,
  };
  // string action_type = 1;
  void clear_action_type();
  const std::string& action_type() const;
  void set_action_type(const std::string& value);
  void set_action_type(std::string&& value);
  void set_action_type(const char* value);
  void set_action_type(const char* value, size_t size);
  std::string* mutable_action_type();
  std::string* release_action_type();
  void set_allocated_action_type(std::string* action_type);
  private:
  const std::string& _internal_action_type() const;
  void _internal_set_action_type(const std::string& value);
  std::string* _internal_mutable_action_type();
  public:

  // int32 action_id = 2;
  void clear_action_id();
  ::PROTOBUF_NAMESPACE_ID::int32 action_id() const;
  void set_action_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_action_id() const;
  void _internal_set_action_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:sts.ai.protocol.v1.ActionCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr action_type_;
  ::PROTOBUF_NAMESPACE_ID::int32 action_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sts_5fv1_2eproto;
};
// -------------------------------------------------------------------

class ProtocolMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sts.ai.protocol.v1.ProtocolMessage) */ {
 public:
  inline ProtocolMessage() : ProtocolMessage(nullptr) {}
  virtual ~ProtocolMessage();

  ProtocolMessage(const ProtocolMessage& from);
  ProtocolMessage(ProtocolMessage&& from) noexcept
    : ProtocolMessage() {
    *this = ::std::move(from);
  }

  inline ProtocolMessage& operator=(const ProtocolMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtocolMessage& operator=(ProtocolMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ProtocolMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProtocolMessage* internal_default_instance() {
    return reinterpret_cast<const ProtocolMessage*>(
               &_ProtocolMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ProtocolMessage& a, ProtocolMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ProtocolMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtocolMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ProtocolMessage* New() const final {
    return CreateMaybeMessage<ProtocolMessage>(nullptr);
  }

  ProtocolMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ProtocolMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ProtocolMessage& from);
  void MergeFrom(const ProtocolMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtocolMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sts.ai.protocol.v1.ProtocolMessage";
  }
  protected:
  explicit ProtocolMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sts_5fv1_2eproto);
    return ::descriptor_table_sts_5fv1_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageTypeFieldNumber = 1,
    kGameStateFieldNumber = 4,
    kActionCmdFieldNumber = 5,
    kSequenceIdFieldNumber = 2,
    kIsWaitingForInputFieldNumber = 3,
    kTimestampFieldNumber = 6,
  };
  // string message_type = 1;
  void clear_message_type();
  const std::string& message_type() const;
  void set_message_type(const std::string& value);
  void set_message_type(std::string&& value);
  void set_message_type(const char* value);
  void set_message_type(const char* value, size_t size);
  std::string* mutable_message_type();
  std::string* release_message_type();
  void set_allocated_message_type(std::string* message_type);
  private:
  const std::string& _internal_message_type() const;
  void _internal_set_message_type(const std::string& value);
  std::string* _internal_mutable_message_type();
  public:

  // .sts.ai.protocol.v1.GameState game_state = 4;
  bool has_game_state() const;
  private:
  bool _internal_has_game_state() const;
  public:
  void clear_game_state();
  const ::sts::ai::protocol::v1::GameState& game_state() const;
  ::sts::ai::protocol::v1::GameState* release_game_state();
  ::sts::ai::protocol::v1::GameState* mutable_game_state();
  void set_allocated_game_state(::sts::ai::protocol::v1::GameState* game_state);
  private:
  const ::sts::ai::protocol::v1::GameState& _internal_game_state() const;
  ::sts::ai::protocol::v1::GameState* _internal_mutable_game_state();
  public:
  void unsafe_arena_set_allocated_game_state(
      ::sts::ai::protocol::v1::GameState* game_state);
  ::sts::ai::protocol::v1::GameState* unsafe_arena_release_game_state();

  // .sts.ai.protocol.v1.ActionCommand action_cmd = 5;
  bool has_action_cmd() const;
  private:
  bool _internal_has_action_cmd() const;
  public:
  void clear_action_cmd();
  const ::sts::ai::protocol::v1::ActionCommand& action_cmd() const;
  ::sts::ai::protocol::v1::ActionCommand* release_action_cmd();
  ::sts::ai::protocol::v1::ActionCommand* mutable_action_cmd();
  void set_allocated_action_cmd(::sts::ai::protocol::v1::ActionCommand* action_cmd);
  private:
  const ::sts::ai::protocol::v1::ActionCommand& _internal_action_cmd() const;
  ::sts::ai::protocol::v1::ActionCommand* _internal_mutable_action_cmd();
  public:
  void unsafe_arena_set_allocated_action_cmd(
      ::sts::ai::protocol::v1::ActionCommand* action_cmd);
  ::sts::ai::protocol::v1::ActionCommand* unsafe_arena_release_action_cmd();

  // int32 sequence_id = 2;
  void clear_sequence_id();
  ::PROTOBUF_NAMESPACE_ID::int32 sequence_id() const;
  void set_sequence_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_sequence_id() const;
  void _internal_set_sequence_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // bool is_waiting_for_input = 3;
  void clear_is_waiting_for_input();
  bool is_waiting_for_input() const;
  void set_is_waiting_for_input(bool value);
  private:
  bool _internal_is_waiting_for_input() const;
  void _internal_set_is_waiting_for_input(bool value);
  public:

  // int64 timestamp = 6;
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:sts.ai.protocol.v1.ProtocolMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_type_;
  ::sts::ai::protocol::v1::GameState* game_state_;
  ::sts::ai::protocol::v1::ActionCommand* action_cmd_;
  ::PROTOBUF_NAMESPACE_ID::int32 sequence_id_;
  bool is_waiting_for_input_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sts_5fv1_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GameState

// string md5_seed = 1;
inline void GameState::clear_md5_seed() {
  md5_seed_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& GameState::md5_seed() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.GameState.md5_seed)
  return _internal_md5_seed();
}
inline void GameState::set_md5_seed(const std::string& value) {
  _internal_set_md5_seed(value);
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.GameState.md5_seed)
}
inline std::string* GameState::mutable_md5_seed() {
  // @@protoc_insertion_point(field_mutable:sts.ai.protocol.v1.GameState.md5_seed)
  return _internal_mutable_md5_seed();
}
inline const std::string& GameState::_internal_md5_seed() const {
  return md5_seed_.Get();
}
inline void GameState::_internal_set_md5_seed(const std::string& value) {
  
  md5_seed_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GameState::set_md5_seed(std::string&& value) {
  
  md5_seed_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sts.ai.protocol.v1.GameState.md5_seed)
}
inline void GameState::set_md5_seed(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  md5_seed_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sts.ai.protocol.v1.GameState.md5_seed)
}
inline void GameState::set_md5_seed(const char* value,
    size_t size) {
  
  md5_seed_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sts.ai.protocol.v1.GameState.md5_seed)
}
inline std::string* GameState::_internal_mutable_md5_seed() {
  
  return md5_seed_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GameState::release_md5_seed() {
  // @@protoc_insertion_point(field_release:sts.ai.protocol.v1.GameState.md5_seed)
  return md5_seed_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GameState::set_allocated_md5_seed(std::string* md5_seed) {
  if (md5_seed != nullptr) {
    
  } else {
    
  }
  md5_seed_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), md5_seed,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sts.ai.protocol.v1.GameState.md5_seed)
}

// string character = 2;
inline void GameState::clear_character() {
  character_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& GameState::character() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.GameState.character)
  return _internal_character();
}
inline void GameState::set_character(const std::string& value) {
  _internal_set_character(value);
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.GameState.character)
}
inline std::string* GameState::mutable_character() {
  // @@protoc_insertion_point(field_mutable:sts.ai.protocol.v1.GameState.character)
  return _internal_mutable_character();
}
inline const std::string& GameState::_internal_character() const {
  return character_.Get();
}
inline void GameState::_internal_set_character(const std::string& value) {
  
  character_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GameState::set_character(std::string&& value) {
  
  character_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sts.ai.protocol.v1.GameState.character)
}
inline void GameState::set_character(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  character_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sts.ai.protocol.v1.GameState.character)
}
inline void GameState::set_character(const char* value,
    size_t size) {
  
  character_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sts.ai.protocol.v1.GameState.character)
}
inline std::string* GameState::_internal_mutable_character() {
  
  return character_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GameState::release_character() {
  // @@protoc_insertion_point(field_release:sts.ai.protocol.v1.GameState.character)
  return character_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GameState::set_allocated_character(std::string* character) {
  if (character != nullptr) {
    
  } else {
    
  }
  character_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), character,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sts.ai.protocol.v1.GameState.character)
}

// int32 act = 3;
inline void GameState::clear_act() {
  act_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameState::_internal_act() const {
  return act_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameState::act() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.GameState.act)
  return _internal_act();
}
inline void GameState::_internal_set_act(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  act_ = value;
}
inline void GameState::set_act(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_act(value);
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.GameState.act)
}

// int32 floor = 4;
inline void GameState::clear_floor() {
  floor_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameState::_internal_floor() const {
  return floor_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameState::floor() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.GameState.floor)
  return _internal_floor();
}
inline void GameState::_internal_set_floor(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  floor_ = value;
}
inline void GameState::set_floor(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_floor(value);
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.GameState.floor)
}

// int32 player_hp = 5;
inline void GameState::clear_player_hp() {
  player_hp_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameState::_internal_player_hp() const {
  return player_hp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameState::player_hp() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.GameState.player_hp)
  return _internal_player_hp();
}
inline void GameState::_internal_set_player_hp(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  player_hp_ = value;
}
inline void GameState::set_player_hp(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_player_hp(value);
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.GameState.player_hp)
}

// int32 player_max_hp = 6;
inline void GameState::clear_player_max_hp() {
  player_max_hp_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameState::_internal_player_max_hp() const {
  return player_max_hp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameState::player_max_hp() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.GameState.player_max_hp)
  return _internal_player_max_hp();
}
inline void GameState::_internal_set_player_max_hp(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  player_max_hp_ = value;
}
inline void GameState::set_player_max_hp(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_player_max_hp(value);
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.GameState.player_max_hp)
}

// int32 player_energy = 7;
inline void GameState::clear_player_energy() {
  player_energy_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameState::_internal_player_energy() const {
  return player_energy_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameState::player_energy() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.GameState.player_energy)
  return _internal_player_energy();
}
inline void GameState::_internal_set_player_energy(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  player_energy_ = value;
}
inline void GameState::set_player_energy(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_player_energy(value);
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.GameState.player_energy)
}

// repeated string hand_cards = 8;
inline int GameState::_internal_hand_cards_size() const {
  return hand_cards_.size();
}
inline int GameState::hand_cards_size() const {
  return _internal_hand_cards_size();
}
inline void GameState::clear_hand_cards() {
  hand_cards_.Clear();
}
inline std::string* GameState::add_hand_cards() {
  // @@protoc_insertion_point(field_add_mutable:sts.ai.protocol.v1.GameState.hand_cards)
  return _internal_add_hand_cards();
}
inline const std::string& GameState::_internal_hand_cards(int index) const {
  return hand_cards_.Get(index);
}
inline const std::string& GameState::hand_cards(int index) const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.GameState.hand_cards)
  return _internal_hand_cards(index);
}
inline std::string* GameState::mutable_hand_cards(int index) {
  // @@protoc_insertion_point(field_mutable:sts.ai.protocol.v1.GameState.hand_cards)
  return hand_cards_.Mutable(index);
}
inline void GameState::set_hand_cards(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.GameState.hand_cards)
  hand_cards_.Mutable(index)->assign(value);
}
inline void GameState::set_hand_cards(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.GameState.hand_cards)
  hand_cards_.Mutable(index)->assign(std::move(value));
}
inline void GameState::set_hand_cards(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  hand_cards_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:sts.ai.protocol.v1.GameState.hand_cards)
}
inline void GameState::set_hand_cards(int index, const char* value, size_t size) {
  hand_cards_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sts.ai.protocol.v1.GameState.hand_cards)
}
inline std::string* GameState::_internal_add_hand_cards() {
  return hand_cards_.Add();
}
inline void GameState::add_hand_cards(const std::string& value) {
  hand_cards_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:sts.ai.protocol.v1.GameState.hand_cards)
}
inline void GameState::add_hand_cards(std::string&& value) {
  hand_cards_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:sts.ai.protocol.v1.GameState.hand_cards)
}
inline void GameState::add_hand_cards(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  hand_cards_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:sts.ai.protocol.v1.GameState.hand_cards)
}
inline void GameState::add_hand_cards(const char* value, size_t size) {
  hand_cards_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:sts.ai.protocol.v1.GameState.hand_cards)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
GameState::hand_cards() const {
  // @@protoc_insertion_point(field_list:sts.ai.protocol.v1.GameState.hand_cards)
  return hand_cards_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
GameState::mutable_hand_cards() {
  // @@protoc_insertion_point(field_mutable_list:sts.ai.protocol.v1.GameState.hand_cards)
  return &hand_cards_;
}

// repeated int32 valid_actions = 9;
inline int GameState::_internal_valid_actions_size() const {
  return valid_actions_.size();
}
inline int GameState::valid_actions_size() const {
  return _internal_valid_actions_size();
}
inline void GameState::clear_valid_actions() {
  valid_actions_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameState::_internal_valid_actions(int index) const {
  return valid_actions_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 GameState::valid_actions(int index) const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.GameState.valid_actions)
  return _internal_valid_actions(index);
}
inline void GameState::set_valid_actions(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  valid_actions_.Set(index, value);
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.GameState.valid_actions)
}
inline void GameState::_internal_add_valid_actions(::PROTOBUF_NAMESPACE_ID::int32 value) {
  valid_actions_.Add(value);
}
inline void GameState::add_valid_actions(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_valid_actions(value);
  // @@protoc_insertion_point(field_add:sts.ai.protocol.v1.GameState.valid_actions)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
GameState::_internal_valid_actions() const {
  return valid_actions_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
GameState::valid_actions() const {
  // @@protoc_insertion_point(field_list:sts.ai.protocol.v1.GameState.valid_actions)
  return _internal_valid_actions();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
GameState::_internal_mutable_valid_actions() {
  return &valid_actions_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
GameState::mutable_valid_actions() {
  // @@protoc_insertion_point(field_mutable_list:sts.ai.protocol.v1.GameState.valid_actions)
  return _internal_mutable_valid_actions();
}

// string stage = 10;
inline void GameState::clear_stage() {
  stage_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& GameState::stage() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.GameState.stage)
  return _internal_stage();
}
inline void GameState::set_stage(const std::string& value) {
  _internal_set_stage(value);
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.GameState.stage)
}
inline std::string* GameState::mutable_stage() {
  // @@protoc_insertion_point(field_mutable:sts.ai.protocol.v1.GameState.stage)
  return _internal_mutable_stage();
}
inline const std::string& GameState::_internal_stage() const {
  return stage_.Get();
}
inline void GameState::_internal_set_stage(const std::string& value) {
  
  stage_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GameState::set_stage(std::string&& value) {
  
  stage_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sts.ai.protocol.v1.GameState.stage)
}
inline void GameState::set_stage(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  stage_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sts.ai.protocol.v1.GameState.stage)
}
inline void GameState::set_stage(const char* value,
    size_t size) {
  
  stage_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sts.ai.protocol.v1.GameState.stage)
}
inline std::string* GameState::_internal_mutable_stage() {
  
  return stage_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GameState::release_stage() {
  // @@protoc_insertion_point(field_release:sts.ai.protocol.v1.GameState.stage)
  return stage_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GameState::set_allocated_stage(std::string* stage) {
  if (stage != nullptr) {
    
  } else {
    
  }
  stage_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), stage,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sts.ai.protocol.v1.GameState.stage)
}

// -------------------------------------------------------------------

// ActionCommand

// string action_type = 1;
inline void ActionCommand::clear_action_type() {
  action_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ActionCommand::action_type() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.ActionCommand.action_type)
  return _internal_action_type();
}
inline void ActionCommand::set_action_type(const std::string& value) {
  _internal_set_action_type(value);
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.ActionCommand.action_type)
}
inline std::string* ActionCommand::mutable_action_type() {
  // @@protoc_insertion_point(field_mutable:sts.ai.protocol.v1.ActionCommand.action_type)
  return _internal_mutable_action_type();
}
inline const std::string& ActionCommand::_internal_action_type() const {
  return action_type_.Get();
}
inline void ActionCommand::_internal_set_action_type(const std::string& value) {
  
  action_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ActionCommand::set_action_type(std::string&& value) {
  
  action_type_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sts.ai.protocol.v1.ActionCommand.action_type)
}
inline void ActionCommand::set_action_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  action_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sts.ai.protocol.v1.ActionCommand.action_type)
}
inline void ActionCommand::set_action_type(const char* value,
    size_t size) {
  
  action_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sts.ai.protocol.v1.ActionCommand.action_type)
}
inline std::string* ActionCommand::_internal_mutable_action_type() {
  
  return action_type_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ActionCommand::release_action_type() {
  // @@protoc_insertion_point(field_release:sts.ai.protocol.v1.ActionCommand.action_type)
  return action_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ActionCommand::set_allocated_action_type(std::string* action_type) {
  if (action_type != nullptr) {
    
  } else {
    
  }
  action_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), action_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sts.ai.protocol.v1.ActionCommand.action_type)
}

// int32 action_id = 2;
inline void ActionCommand::clear_action_id() {
  action_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ActionCommand::_internal_action_id() const {
  return action_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ActionCommand::action_id() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.ActionCommand.action_id)
  return _internal_action_id();
}
inline void ActionCommand::_internal_set_action_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  action_id_ = value;
}
inline void ActionCommand::set_action_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_action_id(value);
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.ActionCommand.action_id)
}

// -------------------------------------------------------------------

// ProtocolMessage

// string message_type = 1;
inline void ProtocolMessage::clear_message_type() {
  message_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ProtocolMessage::message_type() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.ProtocolMessage.message_type)
  return _internal_message_type();
}
inline void ProtocolMessage::set_message_type(const std::string& value) {
  _internal_set_message_type(value);
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.ProtocolMessage.message_type)
}
inline std::string* ProtocolMessage::mutable_message_type() {
  // @@protoc_insertion_point(field_mutable:sts.ai.protocol.v1.ProtocolMessage.message_type)
  return _internal_mutable_message_type();
}
inline const std::string& ProtocolMessage::_internal_message_type() const {
  return message_type_.Get();
}
inline void ProtocolMessage::_internal_set_message_type(const std::string& value) {
  
  message_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ProtocolMessage::set_message_type(std::string&& value) {
  
  message_type_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:sts.ai.protocol.v1.ProtocolMessage.message_type)
}
inline void ProtocolMessage::set_message_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:sts.ai.protocol.v1.ProtocolMessage.message_type)
}
inline void ProtocolMessage::set_message_type(const char* value,
    size_t size) {
  
  message_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:sts.ai.protocol.v1.ProtocolMessage.message_type)
}
inline std::string* ProtocolMessage::_internal_mutable_message_type() {
  
  return message_type_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ProtocolMessage::release_message_type() {
  // @@protoc_insertion_point(field_release:sts.ai.protocol.v1.ProtocolMessage.message_type)
  return message_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ProtocolMessage::set_allocated_message_type(std::string* message_type) {
  if (message_type != nullptr) {
    
  } else {
    
  }
  message_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:sts.ai.protocol.v1.ProtocolMessage.message_type)
}

// int32 sequence_id = 2;
inline void ProtocolMessage::clear_sequence_id() {
  sequence_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ProtocolMessage::_internal_sequence_id() const {
  return sequence_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ProtocolMessage::sequence_id() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.ProtocolMessage.sequence_id)
  return _internal_sequence_id();
}
inline void ProtocolMessage::_internal_set_sequence_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  sequence_id_ = value;
}
inline void ProtocolMessage::set_sequence_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_sequence_id(value);
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.ProtocolMessage.sequence_id)
}

// bool is_waiting_for_input = 3;
inline void ProtocolMessage::clear_is_waiting_for_input() {
  is_waiting_for_input_ = false;
}
inline bool ProtocolMessage::_internal_is_waiting_for_input() const {
  return is_waiting_for_input_;
}
inline bool ProtocolMessage::is_waiting_for_input() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.ProtocolMessage.is_waiting_for_input)
  return _internal_is_waiting_for_input();
}
inline void ProtocolMessage::_internal_set_is_waiting_for_input(bool value) {
  
  is_waiting_for_input_ = value;
}
inline void ProtocolMessage::set_is_waiting_for_input(bool value) {
  _internal_set_is_waiting_for_input(value);
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.ProtocolMessage.is_waiting_for_input)
}

// .sts.ai.protocol.v1.GameState game_state = 4;
inline bool ProtocolMessage::_internal_has_game_state() const {
  return this != internal_default_instance() && game_state_ != nullptr;
}
inline bool ProtocolMessage::has_game_state() const {
  return _internal_has_game_state();
}
inline void ProtocolMessage::clear_game_state() {
  if (GetArena() == nullptr && game_state_ != nullptr) {
    delete game_state_;
  }
  game_state_ = nullptr;
}
inline const ::sts::ai::protocol::v1::GameState& ProtocolMessage::_internal_game_state() const {
  const ::sts::ai::protocol::v1::GameState* p = game_state_;
  return p != nullptr ? *p : *reinterpret_cast<const ::sts::ai::protocol::v1::GameState*>(
      &::sts::ai::protocol::v1::_GameState_default_instance_);
}
inline const ::sts::ai::protocol::v1::GameState& ProtocolMessage::game_state() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.ProtocolMessage.game_state)
  return _internal_game_state();
}
inline void ProtocolMessage::unsafe_arena_set_allocated_game_state(
    ::sts::ai::protocol::v1::GameState* game_state) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(game_state_);
  }
  game_state_ = game_state;
  if (game_state) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sts.ai.protocol.v1.ProtocolMessage.game_state)
}
inline ::sts::ai::protocol::v1::GameState* ProtocolMessage::release_game_state() {
  
  ::sts::ai::protocol::v1::GameState* temp = game_state_;
  game_state_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::sts::ai::protocol::v1::GameState* ProtocolMessage::unsafe_arena_release_game_state() {
  // @@protoc_insertion_point(field_release:sts.ai.protocol.v1.ProtocolMessage.game_state)
  
  ::sts::ai::protocol::v1::GameState* temp = game_state_;
  game_state_ = nullptr;
  return temp;
}
inline ::sts::ai::protocol::v1::GameState* ProtocolMessage::_internal_mutable_game_state() {
  
  if (game_state_ == nullptr) {
    auto* p = CreateMaybeMessage<::sts::ai::protocol::v1::GameState>(GetArena());
    game_state_ = p;
  }
  return game_state_;
}
inline ::sts::ai::protocol::v1::GameState* ProtocolMessage::mutable_game_state() {
  // @@protoc_insertion_point(field_mutable:sts.ai.protocol.v1.ProtocolMessage.game_state)
  return _internal_mutable_game_state();
}
inline void ProtocolMessage::set_allocated_game_state(::sts::ai::protocol::v1::GameState* game_state) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete game_state_;
  }
  if (game_state) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(game_state);
    if (message_arena != submessage_arena) {
      game_state = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, game_state, submessage_arena);
    }
    
  } else {
    
  }
  game_state_ = game_state;
  // @@protoc_insertion_point(field_set_allocated:sts.ai.protocol.v1.ProtocolMessage.game_state)
}

// .sts.ai.protocol.v1.ActionCommand action_cmd = 5;
inline bool ProtocolMessage::_internal_has_action_cmd() const {
  return this != internal_default_instance() && action_cmd_ != nullptr;
}
inline bool ProtocolMessage::has_action_cmd() const {
  return _internal_has_action_cmd();
}
inline void ProtocolMessage::clear_action_cmd() {
  if (GetArena() == nullptr && action_cmd_ != nullptr) {
    delete action_cmd_;
  }
  action_cmd_ = nullptr;
}
inline const ::sts::ai::protocol::v1::ActionCommand& ProtocolMessage::_internal_action_cmd() const {
  const ::sts::ai::protocol::v1::ActionCommand* p = action_cmd_;
  return p != nullptr ? *p : *reinterpret_cast<const ::sts::ai::protocol::v1::ActionCommand*>(
      &::sts::ai::protocol::v1::_ActionCommand_default_instance_);
}
inline const ::sts::ai::protocol::v1::ActionCommand& ProtocolMessage::action_cmd() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.ProtocolMessage.action_cmd)
  return _internal_action_cmd();
}
inline void ProtocolMessage::unsafe_arena_set_allocated_action_cmd(
    ::sts::ai::protocol::v1::ActionCommand* action_cmd) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(action_cmd_);
  }
  action_cmd_ = action_cmd;
  if (action_cmd) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sts.ai.protocol.v1.ProtocolMessage.action_cmd)
}
inline ::sts::ai::protocol::v1::ActionCommand* ProtocolMessage::release_action_cmd() {
  
  ::sts::ai::protocol::v1::ActionCommand* temp = action_cmd_;
  action_cmd_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::sts::ai::protocol::v1::ActionCommand* ProtocolMessage::unsafe_arena_release_action_cmd() {
  // @@protoc_insertion_point(field_release:sts.ai.protocol.v1.ProtocolMessage.action_cmd)
  
  ::sts::ai::protocol::v1::ActionCommand* temp = action_cmd_;
  action_cmd_ = nullptr;
  return temp;
}
inline ::sts::ai::protocol::v1::ActionCommand* ProtocolMessage::_internal_mutable_action_cmd() {
  
  if (action_cmd_ == nullptr) {
    auto* p = CreateMaybeMessage<::sts::ai::protocol::v1::ActionCommand>(GetArena());
    action_cmd_ = p;
  }
  return action_cmd_;
}
inline ::sts::ai::protocol::v1::ActionCommand* ProtocolMessage::mutable_action_cmd() {
  // @@protoc_insertion_point(field_mutable:sts.ai.protocol.v1.ProtocolMessage.action_cmd)
  return _internal_mutable_action_cmd();
}
inline void ProtocolMessage::set_allocated_action_cmd(::sts::ai::protocol::v1::ActionCommand* action_cmd) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete action_cmd_;
  }
  if (action_cmd) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(action_cmd);
    if (message_arena != submessage_arena) {
      action_cmd = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, action_cmd, submessage_arena);
    }
    
  } else {
    
  }
  action_cmd_ = action_cmd;
  // @@protoc_insertion_point(field_set_allocated:sts.ai.protocol.v1.ProtocolMessage.action_cmd)
}

// int64 timestamp = 6;
inline void ProtocolMessage::clear_timestamp() {
  timestamp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ProtocolMessage::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ProtocolMessage::timestamp() const {
  // @@protoc_insertion_point(field_get:sts.ai.protocol.v1.ProtocolMessage.timestamp)
  return _internal_timestamp();
}
inline void ProtocolMessage::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  timestamp_ = value;
}
inline void ProtocolMessage::set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:sts.ai.protocol.v1.ProtocolMessage.timestamp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace protocol
}  // namespace ai
}  // namespace sts

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sts_5fv1_2eproto
