// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sts_v1.proto

#include "sts_v1.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_sts_5fv1_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ActionCommand_sts_5fv1_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_sts_5fv1_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GameState_sts_5fv1_2eproto;
namespace sts {
namespace ai {
namespace protocol {
namespace v1 {
class GameStateDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GameState> _instance;
} _GameState_default_instance_;
class ActionCommandDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ActionCommand> _instance;
} _ActionCommand_default_instance_;
class ProtocolMessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ProtocolMessage> _instance;
} _ProtocolMessage_default_instance_;
}  // namespace v1
}  // namespace protocol
}  // namespace ai
}  // namespace sts
static void InitDefaultsscc_info_ActionCommand_sts_5fv1_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sts::ai::protocol::v1::_ActionCommand_default_instance_;
    new (ptr) ::sts::ai::protocol::v1::ActionCommand();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sts::ai::protocol::v1::ActionCommand::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ActionCommand_sts_5fv1_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ActionCommand_sts_5fv1_2eproto}, {}};

static void InitDefaultsscc_info_GameState_sts_5fv1_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sts::ai::protocol::v1::_GameState_default_instance_;
    new (ptr) ::sts::ai::protocol::v1::GameState();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sts::ai::protocol::v1::GameState::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GameState_sts_5fv1_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GameState_sts_5fv1_2eproto}, {}};

static void InitDefaultsscc_info_ProtocolMessage_sts_5fv1_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sts::ai::protocol::v1::_ProtocolMessage_default_instance_;
    new (ptr) ::sts::ai::protocol::v1::ProtocolMessage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sts::ai::protocol::v1::ProtocolMessage::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_ProtocolMessage_sts_5fv1_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_ProtocolMessage_sts_5fv1_2eproto}, {
      &scc_info_GameState_sts_5fv1_2eproto.base,
      &scc_info_ActionCommand_sts_5fv1_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_sts_5fv1_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_sts_5fv1_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_sts_5fv1_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_sts_5fv1_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::GameState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::GameState, md5_seed_),
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::GameState, character_),
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::GameState, act_),
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::GameState, floor_),
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::GameState, player_hp_),
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::GameState, player_max_hp_),
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::GameState, player_energy_),
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::GameState, hand_cards_),
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::GameState, valid_actions_),
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::GameState, stage_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::ActionCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::ActionCommand, action_type_),
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::ActionCommand, action_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::ProtocolMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::ProtocolMessage, message_type_),
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::ProtocolMessage, sequence_id_),
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::ProtocolMessage, is_waiting_for_input_),
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::ProtocolMessage, game_state_),
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::ProtocolMessage, action_cmd_),
  PROTOBUF_FIELD_OFFSET(::sts::ai::protocol::v1::ProtocolMessage, timestamp_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::sts::ai::protocol::v1::GameState)},
  { 15, -1, sizeof(::sts::ai::protocol::v1::ActionCommand)},
  { 22, -1, sizeof(::sts::ai::protocol::v1::ProtocolMessage)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::sts::ai::protocol::v1::_GameState_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::sts::ai::protocol::v1::_ActionCommand_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::sts::ai::protocol::v1::_ProtocolMessage_default_instance_),
};

const char descriptor_table_protodef_sts_5fv1_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014sts_v1.proto\022\022sts.ai.protocol.v1\"\307\001\n\tG"
  "ameState\022\020\n\010md5_seed\030\001 \001(\t\022\021\n\tcharacter\030"
  "\002 \001(\t\022\013\n\003act\030\003 \001(\005\022\r\n\005floor\030\004 \001(\005\022\021\n\tpla"
  "yer_hp\030\005 \001(\005\022\025\n\rplayer_max_hp\030\006 \001(\005\022\025\n\rp"
  "layer_energy\030\007 \001(\005\022\022\n\nhand_cards\030\010 \003(\t\022\025"
  "\n\rvalid_actions\030\t \003(\005\022\r\n\005stage\030\n \001(\t\"7\n\r"
  "ActionCommand\022\023\n\013action_type\030\001 \001(\t\022\021\n\tac"
  "tion_id\030\002 \001(\005\"\327\001\n\017ProtocolMessage\022\024\n\014mes"
  "sage_type\030\001 \001(\t\022\023\n\013sequence_id\030\002 \001(\005\022\034\n\024"
  "is_waiting_for_input\030\003 \001(\010\0221\n\ngame_state"
  "\030\004 \001(\0132\035.sts.ai.protocol.v1.GameState\0225\n"
  "\naction_cmd\030\005 \001(\0132!.sts.ai.protocol.v1.A"
  "ctionCommand\022\021\n\ttimestamp\030\006 \001(\003b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_sts_5fv1_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_sts_5fv1_2eproto_sccs[3] = {
  &scc_info_ActionCommand_sts_5fv1_2eproto.base,
  &scc_info_GameState_sts_5fv1_2eproto.base,
  &scc_info_ProtocolMessage_sts_5fv1_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_sts_5fv1_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sts_5fv1_2eproto = {
  false, false, descriptor_table_protodef_sts_5fv1_2eproto, "sts_v1.proto", 519,
  &descriptor_table_sts_5fv1_2eproto_once, descriptor_table_sts_5fv1_2eproto_sccs, descriptor_table_sts_5fv1_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_sts_5fv1_2eproto::offsets,
  file_level_metadata_sts_5fv1_2eproto, 3, file_level_enum_descriptors_sts_5fv1_2eproto, file_level_service_descriptors_sts_5fv1_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_sts_5fv1_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_sts_5fv1_2eproto)), true);
namespace sts {
namespace ai {
namespace protocol {
namespace v1 {

// ===================================================================

void GameState::InitAsDefaultInstance() {
}
class GameState::_Internal {
 public:
};

GameState::GameState(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  hand_cards_(arena),
  valid_actions_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:sts.ai.protocol.v1.GameState)
}
GameState::GameState(const GameState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      hand_cards_(from.hand_cards_),
      valid_actions_(from.valid_actions_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  md5_seed_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_md5_seed().empty()) {
    md5_seed_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_md5_seed(),
      GetArena());
  }
  character_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_character().empty()) {
    character_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_character(),
      GetArena());
  }
  stage_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_stage().empty()) {
    stage_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_stage(),
      GetArena());
  }
  ::memcpy(&act_, &from.act_,
    static_cast<size_t>(reinterpret_cast<char*>(&player_energy_) -
    reinterpret_cast<char*>(&act_)) + sizeof(player_energy_));
  // @@protoc_insertion_point(copy_constructor:sts.ai.protocol.v1.GameState)
}

void GameState::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GameState_sts_5fv1_2eproto.base);
  md5_seed_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  character_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  stage_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&act_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&player_energy_) -
      reinterpret_cast<char*>(&act_)) + sizeof(player_energy_));
}

GameState::~GameState() {
  // @@protoc_insertion_point(destructor:sts.ai.protocol.v1.GameState)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GameState::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  md5_seed_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  character_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  stage_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void GameState::ArenaDtor(void* object) {
  GameState* _this = reinterpret_cast< GameState* >(object);
  (void)_this;
}
void GameState::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GameState::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GameState& GameState::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GameState_sts_5fv1_2eproto.base);
  return *internal_default_instance();
}


void GameState::Clear() {
// @@protoc_insertion_point(message_clear_start:sts.ai.protocol.v1.GameState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  hand_cards_.Clear();
  valid_actions_.Clear();
  md5_seed_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  character_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  stage_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&act_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&player_energy_) -
      reinterpret_cast<char*>(&act_)) + sizeof(player_energy_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GameState::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string md5_seed = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_md5_seed();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "sts.ai.protocol.v1.GameState.md5_seed"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string character = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_character();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "sts.ai.protocol.v1.GameState.character"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 act = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          act_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 floor = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          floor_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 player_hp = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          player_hp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 player_max_hp = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          player_max_hp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 player_energy = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          player_energy_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated string hand_cards = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_hand_cards();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "sts.ai.protocol.v1.GameState.hand_cards"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<66>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated int32 valid_actions = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_valid_actions(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72) {
          _internal_add_valid_actions(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string stage = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          auto str = _internal_mutable_stage();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "sts.ai.protocol.v1.GameState.stage"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GameState::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sts.ai.protocol.v1.GameState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string md5_seed = 1;
  if (this->md5_seed().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_md5_seed().data(), static_cast<int>(this->_internal_md5_seed().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sts.ai.protocol.v1.GameState.md5_seed");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_md5_seed(), target);
  }

  // string character = 2;
  if (this->character().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_character().data(), static_cast<int>(this->_internal_character().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sts.ai.protocol.v1.GameState.character");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_character(), target);
  }

  // int32 act = 3;
  if (this->act() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_act(), target);
  }

  // int32 floor = 4;
  if (this->floor() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_floor(), target);
  }

  // int32 player_hp = 5;
  if (this->player_hp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_player_hp(), target);
  }

  // int32 player_max_hp = 6;
  if (this->player_max_hp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(6, this->_internal_player_max_hp(), target);
  }

  // int32 player_energy = 7;
  if (this->player_energy() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(7, this->_internal_player_energy(), target);
  }

  // repeated string hand_cards = 8;
  for (int i = 0, n = this->_internal_hand_cards_size(); i < n; i++) {
    const auto& s = this->_internal_hand_cards(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sts.ai.protocol.v1.GameState.hand_cards");
    target = stream->WriteString(8, s, target);
  }

  // repeated int32 valid_actions = 9;
  {
    int byte_size = _valid_actions_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          9, _internal_valid_actions(), byte_size, target);
    }
  }

  // string stage = 10;
  if (this->stage().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_stage().data(), static_cast<int>(this->_internal_stage().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sts.ai.protocol.v1.GameState.stage");
    target = stream->WriteStringMaybeAliased(
        10, this->_internal_stage(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sts.ai.protocol.v1.GameState)
  return target;
}

size_t GameState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sts.ai.protocol.v1.GameState)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string hand_cards = 8;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(hand_cards_.size());
  for (int i = 0, n = hand_cards_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      hand_cards_.Get(i));
  }

  // repeated int32 valid_actions = 9;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      Int32Size(this->valid_actions_);
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _valid_actions_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // string md5_seed = 1;
  if (this->md5_seed().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_md5_seed());
  }

  // string character = 2;
  if (this->character().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_character());
  }

  // string stage = 10;
  if (this->stage().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_stage());
  }

  // int32 act = 3;
  if (this->act() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_act());
  }

  // int32 floor = 4;
  if (this->floor() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_floor());
  }

  // int32 player_hp = 5;
  if (this->player_hp() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_player_hp());
  }

  // int32 player_max_hp = 6;
  if (this->player_max_hp() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_player_max_hp());
  }

  // int32 player_energy = 7;
  if (this->player_energy() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_player_energy());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GameState::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sts.ai.protocol.v1.GameState)
  GOOGLE_DCHECK_NE(&from, this);
  const GameState* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GameState>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sts.ai.protocol.v1.GameState)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sts.ai.protocol.v1.GameState)
    MergeFrom(*source);
  }
}

void GameState::MergeFrom(const GameState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sts.ai.protocol.v1.GameState)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  hand_cards_.MergeFrom(from.hand_cards_);
  valid_actions_.MergeFrom(from.valid_actions_);
  if (from.md5_seed().size() > 0) {
    _internal_set_md5_seed(from._internal_md5_seed());
  }
  if (from.character().size() > 0) {
    _internal_set_character(from._internal_character());
  }
  if (from.stage().size() > 0) {
    _internal_set_stage(from._internal_stage());
  }
  if (from.act() != 0) {
    _internal_set_act(from._internal_act());
  }
  if (from.floor() != 0) {
    _internal_set_floor(from._internal_floor());
  }
  if (from.player_hp() != 0) {
    _internal_set_player_hp(from._internal_player_hp());
  }
  if (from.player_max_hp() != 0) {
    _internal_set_player_max_hp(from._internal_player_max_hp());
  }
  if (from.player_energy() != 0) {
    _internal_set_player_energy(from._internal_player_energy());
  }
}

void GameState::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sts.ai.protocol.v1.GameState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GameState::CopyFrom(const GameState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sts.ai.protocol.v1.GameState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameState::IsInitialized() const {
  return true;
}

void GameState::InternalSwap(GameState* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  hand_cards_.InternalSwap(&other->hand_cards_);
  valid_actions_.InternalSwap(&other->valid_actions_);
  md5_seed_.Swap(&other->md5_seed_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  character_.Swap(&other->character_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  stage_.Swap(&other->stage_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GameState, player_energy_)
      + sizeof(GameState::player_energy_)
      - PROTOBUF_FIELD_OFFSET(GameState, act_)>(
          reinterpret_cast<char*>(&act_),
          reinterpret_cast<char*>(&other->act_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GameState::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ActionCommand::InitAsDefaultInstance() {
}
class ActionCommand::_Internal {
 public:
};

ActionCommand::ActionCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:sts.ai.protocol.v1.ActionCommand)
}
ActionCommand::ActionCommand(const ActionCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  action_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_action_type().empty()) {
    action_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_action_type(),
      GetArena());
  }
  action_id_ = from.action_id_;
  // @@protoc_insertion_point(copy_constructor:sts.ai.protocol.v1.ActionCommand)
}

void ActionCommand::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ActionCommand_sts_5fv1_2eproto.base);
  action_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  action_id_ = 0;
}

ActionCommand::~ActionCommand() {
  // @@protoc_insertion_point(destructor:sts.ai.protocol.v1.ActionCommand)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ActionCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  action_type_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ActionCommand::ArenaDtor(void* object) {
  ActionCommand* _this = reinterpret_cast< ActionCommand* >(object);
  (void)_this;
}
void ActionCommand::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ActionCommand::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ActionCommand& ActionCommand::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ActionCommand_sts_5fv1_2eproto.base);
  return *internal_default_instance();
}


void ActionCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:sts.ai.protocol.v1.ActionCommand)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  action_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  action_id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ActionCommand::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string action_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_action_type();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "sts.ai.protocol.v1.ActionCommand.action_type"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 action_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          action_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ActionCommand::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sts.ai.protocol.v1.ActionCommand)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string action_type = 1;
  if (this->action_type().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_action_type().data(), static_cast<int>(this->_internal_action_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sts.ai.protocol.v1.ActionCommand.action_type");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_action_type(), target);
  }

  // int32 action_id = 2;
  if (this->action_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_action_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sts.ai.protocol.v1.ActionCommand)
  return target;
}

size_t ActionCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sts.ai.protocol.v1.ActionCommand)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string action_type = 1;
  if (this->action_type().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_action_type());
  }

  // int32 action_id = 2;
  if (this->action_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_action_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ActionCommand::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sts.ai.protocol.v1.ActionCommand)
  GOOGLE_DCHECK_NE(&from, this);
  const ActionCommand* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ActionCommand>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sts.ai.protocol.v1.ActionCommand)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sts.ai.protocol.v1.ActionCommand)
    MergeFrom(*source);
  }
}

void ActionCommand::MergeFrom(const ActionCommand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sts.ai.protocol.v1.ActionCommand)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.action_type().size() > 0) {
    _internal_set_action_type(from._internal_action_type());
  }
  if (from.action_id() != 0) {
    _internal_set_action_id(from._internal_action_id());
  }
}

void ActionCommand::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sts.ai.protocol.v1.ActionCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ActionCommand::CopyFrom(const ActionCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sts.ai.protocol.v1.ActionCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActionCommand::IsInitialized() const {
  return true;
}

void ActionCommand::InternalSwap(ActionCommand* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  action_type_.Swap(&other->action_type_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(action_id_, other->action_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ActionCommand::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ProtocolMessage::InitAsDefaultInstance() {
  ::sts::ai::protocol::v1::_ProtocolMessage_default_instance_._instance.get_mutable()->game_state_ = const_cast< ::sts::ai::protocol::v1::GameState*>(
      ::sts::ai::protocol::v1::GameState::internal_default_instance());
  ::sts::ai::protocol::v1::_ProtocolMessage_default_instance_._instance.get_mutable()->action_cmd_ = const_cast< ::sts::ai::protocol::v1::ActionCommand*>(
      ::sts::ai::protocol::v1::ActionCommand::internal_default_instance());
}
class ProtocolMessage::_Internal {
 public:
  static const ::sts::ai::protocol::v1::GameState& game_state(const ProtocolMessage* msg);
  static const ::sts::ai::protocol::v1::ActionCommand& action_cmd(const ProtocolMessage* msg);
};

const ::sts::ai::protocol::v1::GameState&
ProtocolMessage::_Internal::game_state(const ProtocolMessage* msg) {
  return *msg->game_state_;
}
const ::sts::ai::protocol::v1::ActionCommand&
ProtocolMessage::_Internal::action_cmd(const ProtocolMessage* msg) {
  return *msg->action_cmd_;
}
ProtocolMessage::ProtocolMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:sts.ai.protocol.v1.ProtocolMessage)
}
ProtocolMessage::ProtocolMessage(const ProtocolMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  message_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_message_type().empty()) {
    message_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_message_type(),
      GetArena());
  }
  if (from._internal_has_game_state()) {
    game_state_ = new ::sts::ai::protocol::v1::GameState(*from.game_state_);
  } else {
    game_state_ = nullptr;
  }
  if (from._internal_has_action_cmd()) {
    action_cmd_ = new ::sts::ai::protocol::v1::ActionCommand(*from.action_cmd_);
  } else {
    action_cmd_ = nullptr;
  }
  ::memcpy(&sequence_id_, &from.sequence_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&timestamp_) -
    reinterpret_cast<char*>(&sequence_id_)) + sizeof(timestamp_));
  // @@protoc_insertion_point(copy_constructor:sts.ai.protocol.v1.ProtocolMessage)
}

void ProtocolMessage::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ProtocolMessage_sts_5fv1_2eproto.base);
  message_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&game_state_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&timestamp_) -
      reinterpret_cast<char*>(&game_state_)) + sizeof(timestamp_));
}

ProtocolMessage::~ProtocolMessage() {
  // @@protoc_insertion_point(destructor:sts.ai.protocol.v1.ProtocolMessage)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ProtocolMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  message_type_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete game_state_;
  if (this != internal_default_instance()) delete action_cmd_;
}

void ProtocolMessage::ArenaDtor(void* object) {
  ProtocolMessage* _this = reinterpret_cast< ProtocolMessage* >(object);
  (void)_this;
}
void ProtocolMessage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ProtocolMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ProtocolMessage& ProtocolMessage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ProtocolMessage_sts_5fv1_2eproto.base);
  return *internal_default_instance();
}


void ProtocolMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:sts.ai.protocol.v1.ProtocolMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && game_state_ != nullptr) {
    delete game_state_;
  }
  game_state_ = nullptr;
  if (GetArena() == nullptr && action_cmd_ != nullptr) {
    delete action_cmd_;
  }
  action_cmd_ = nullptr;
  ::memset(&sequence_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&timestamp_) -
      reinterpret_cast<char*>(&sequence_id_)) + sizeof(timestamp_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProtocolMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string message_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_message_type();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "sts.ai.protocol.v1.ProtocolMessage.message_type"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 sequence_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          sequence_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool is_waiting_for_input = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          is_waiting_for_input_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .sts.ai.protocol.v1.GameState game_state = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_game_state(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .sts.ai.protocol.v1.ActionCommand action_cmd = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_action_cmd(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 timestamp = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ProtocolMessage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sts.ai.protocol.v1.ProtocolMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string message_type = 1;
  if (this->message_type().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message_type().data(), static_cast<int>(this->_internal_message_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sts.ai.protocol.v1.ProtocolMessage.message_type");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_message_type(), target);
  }

  // int32 sequence_id = 2;
  if (this->sequence_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_sequence_id(), target);
  }

  // bool is_waiting_for_input = 3;
  if (this->is_waiting_for_input() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_is_waiting_for_input(), target);
  }

  // .sts.ai.protocol.v1.GameState game_state = 4;
  if (this->has_game_state()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::game_state(this), target, stream);
  }

  // .sts.ai.protocol.v1.ActionCommand action_cmd = 5;
  if (this->has_action_cmd()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::action_cmd(this), target, stream);
  }

  // int64 timestamp = 6;
  if (this->timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(6, this->_internal_timestamp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sts.ai.protocol.v1.ProtocolMessage)
  return target;
}

size_t ProtocolMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sts.ai.protocol.v1.ProtocolMessage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message_type = 1;
  if (this->message_type().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message_type());
  }

  // .sts.ai.protocol.v1.GameState game_state = 4;
  if (this->has_game_state()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *game_state_);
  }

  // .sts.ai.protocol.v1.ActionCommand action_cmd = 5;
  if (this->has_action_cmd()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *action_cmd_);
  }

  // int32 sequence_id = 2;
  if (this->sequence_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_sequence_id());
  }

  // bool is_waiting_for_input = 3;
  if (this->is_waiting_for_input() != 0) {
    total_size += 1 + 1;
  }

  // int64 timestamp = 6;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_timestamp());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ProtocolMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sts.ai.protocol.v1.ProtocolMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const ProtocolMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ProtocolMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sts.ai.protocol.v1.ProtocolMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sts.ai.protocol.v1.ProtocolMessage)
    MergeFrom(*source);
  }
}

void ProtocolMessage::MergeFrom(const ProtocolMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sts.ai.protocol.v1.ProtocolMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message_type().size() > 0) {
    _internal_set_message_type(from._internal_message_type());
  }
  if (from.has_game_state()) {
    _internal_mutable_game_state()->::sts::ai::protocol::v1::GameState::MergeFrom(from._internal_game_state());
  }
  if (from.has_action_cmd()) {
    _internal_mutable_action_cmd()->::sts::ai::protocol::v1::ActionCommand::MergeFrom(from._internal_action_cmd());
  }
  if (from.sequence_id() != 0) {
    _internal_set_sequence_id(from._internal_sequence_id());
  }
  if (from.is_waiting_for_input() != 0) {
    _internal_set_is_waiting_for_input(from._internal_is_waiting_for_input());
  }
  if (from.timestamp() != 0) {
    _internal_set_timestamp(from._internal_timestamp());
  }
}

void ProtocolMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sts.ai.protocol.v1.ProtocolMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProtocolMessage::CopyFrom(const ProtocolMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sts.ai.protocol.v1.ProtocolMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtocolMessage::IsInitialized() const {
  return true;
}

void ProtocolMessage::InternalSwap(ProtocolMessage* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  message_type_.Swap(&other->message_type_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtocolMessage, timestamp_)
      + sizeof(ProtocolMessage::timestamp_)
      - PROTOBUF_FIELD_OFFSET(ProtocolMessage, game_state_)>(
          reinterpret_cast<char*>(&game_state_),
          reinterpret_cast<char*>(&other->game_state_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ProtocolMessage::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace protocol
}  // namespace ai
}  // namespace sts
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sts::ai::protocol::v1::GameState* Arena::CreateMaybeMessage< ::sts::ai::protocol::v1::GameState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sts::ai::protocol::v1::GameState >(arena);
}
template<> PROTOBUF_NOINLINE ::sts::ai::protocol::v1::ActionCommand* Arena::CreateMaybeMessage< ::sts::ai::protocol::v1::ActionCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sts::ai::protocol::v1::ActionCommand >(arena);
}
template<> PROTOBUF_NOINLINE ::sts::ai::protocol::v1::ProtocolMessage* Arena::CreateMaybeMessage< ::sts::ai::protocol::v1::ProtocolMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sts::ai::protocol::v1::ProtocolMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
